src/Goceen.Website.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Goceen.Website.Services;
using Goceen.Website.Domain;
using Leon.Core.Cache;
using Goceen.Website.Web.Extensions;

namespace Goceen.Website.Web.Controllers
{
    public class CategoryController : BaseController
    {

        public CategoryController(ISysConfigService config, ICacheManager cache, ISysUserService user,
            ISysChannelService channel, ISysCategoryService category)
        {
            _cacheManager = cache;
            _sysuserSerice = user;
            _syscategoryService = category;
            _sysconfigService = config;
            _syschannelService = channel;
        }

        [Authorize]
        public ActionResult Admin()
        {
            ViewBag.Title = "分类管理";
            return View();
        }

        [Authorize]
        public ActionResult LoadAllByPage(int page, int rows, string order, string sort)
        {
            long total = 0;
            var list = _syscategoryService.LoadAllByPage(out total, page, rows, order, sort).Select(entity => new
            {
                entity.Name,
                entity.Id,
                entity.OrderNo,
                entity.IsEnabled,
                entity.CategoryType,
                entity.Url,
                ChannelName = entity.Channel.Name,
                ChannelId = entity.Channel.Id
            });

            var result = new { total = total, rows = list.ToList() };
            return Json(result);
        }

        [Authorize]
        public ActionResult AddOrEdit(int? id)
        {
            var channellist = _syschannelService.LoadAllEnable();
            
            var list = channellist.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });
            ViewBag.ChannelList = list.ToList<SelectListItem>();
            //ViewBag.ChannelList = list.Select(x => new SelectListItem { Text=x.Name,Value=x.Id.ToString() });
            SysCategory entity = null;
            ViewBag.Title = "添加分类";
            if (id.HasValue)
            {
                entity = _syscategoryService.Get(id.Value);
                ViewBag.Title = "修改分类";
            }
            entity = entity ?? new SysCategory
            {
                Name = string.Empty,
                
            };
            ViewBag.CategoryType = ExSelectListItem.ToSelectListItem(typeof(CategoryType));
            return View(entity);
        }

        [Authorize]        
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Save(SysCategory entity,int? channelId)
        {
            if (ModelState.IsValid)
            {
                var forum = _syschannelService.Get(channelId.Value);
                if (forum == null)
                {
                    return Json(new CommonResult
                    {
                        Success = false,
                        Message = "未选择频道，保存失败！"
                    }, "text/html", JsonRequestBehavior.AllowGet);
                }
                if (entity.Id == 0)
                {
                    if (_syscategoryService.IsExist(entity.Name.Trim()))
                    {
                        return Json(new CommonResult
                        {
                            Success = false,
                            Message = "分类名称已经存在，请重新输入！"
                        }, "text/html", JsonRequestBehavior.AllowGet);
                    }
                    entity.Channel = forum;
                    base._syscategoryService.Save(entity);
                }
                else
                {
                    var model = base._syscategoryService.Get(entity.Id);
                    model.Name = entity.Name;
                    model.OrderNo = entity.OrderNo;
                    model.IsEnabled = entity.IsEnabled;
                    model.CategoryType = entity.CategoryType;
                    model.Content = entity.Content;
                    model.Url = entity.Url;
                    entity.Channel = forum;
                    base._syscategoryService.Update(model);
                }

                return Json(new CommonResult { Success = true, Message = "保存成功" }, "text/html", JsonRequestBehavior.AllowGet);
            }
            return RedirectToAction("AddOrEdit", entity);
        }

        // GET: Category
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult Delete(IList<int> idList)
        {
            _syscategoryService.Delete(idList);
            return Json(new CommonResult{ Success = true, Message = "删除成功" });
        }
    }
}

src/Goceen.Website.Web/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;
using System.Web.Mvc;
using System.Web.Security;
using Newtonsoft.Json;

namespace Goceen.Website.Web.Controllers
{
    public class UploadController : Controller
    {
        //
        // GET: /Upload/

        protected readonly int maxFileSize = 20480;

        protected readonly string allowFile = "gif,jpg,jpeg,bmp,png";

        protected readonly string uploadPath = "/Content/Upload/image/";

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult UmeditorUploadImg()
        {
            HttpFileCollectionBase files= Request.Files;

            if (files.Count == 0)
            {               
                return Json(new { Success = false, state = "没有选择要上传的文件",URL="" }, "text/html", JsonRequestBehavior.AllowGet);
            }
            HttpPostedFileBase Filedata = files[0];
            string fileName = System.IO.Path.GetFileName(Filedata.FileName);
            // 0字节文件
            if (string.IsNullOrEmpty(fileName) || Filedata.ContentLength < 1)
            {
                return Json(new { Success = false, state = "上传的文件字节数为0" ,URL=""}, "text/html", JsonRequestBehavior.AllowGet);
            }
            if (Filedata.ContentLength > maxFileSize * 1024)
            {
                return Json(new { Success = false, state = "上传的文件大小超过限制，请上传2M以内的图片！", URL = "" }, "text/html", JsonRequestBehavior.AllowGet);
            }

            string fileExt = fileName.Substring(fileName.LastIndexOf(".") + 1).ToLower();
            string newFileName = this.MD5(DateTime.Now.ToString() + new Random().Next(0, 20)).Substring(8, 16).Replace(".", string.Empty).Trim();

            string path = string.Concat(uploadPath, (DateTime.Now.ToString("yyyyMM")), "/");
            if (!Directory.Exists(Server.MapPath(path)))
            {
                Directory.CreateDirectory(Server.MapPath(path));
            }
            string filepath = path + newFileName + "." + fileExt;
            Filedata.SaveAs(Server.MapPath(filepath));

            return Json(new { state = "SUCCESS", url = filepath }, "text/html", JsonRequestBehavior.AllowGet);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult UploadImg(HttpPostedFileBase Filedata)
        {


            if (Filedata == null || string.IsNullOrEmpty(Filedata.FileName) || Filedata.ContentLength == 0)
            {
                return Json(new { Success = false, Message = "没有选择要上传的文件" }, "text/html", JsonRequestBehavior.AllowGet);
            }
            string fileName = System.IO.Path.GetFileName(Filedata.FileName);
            // 0字节文件
            if (string.IsNullOrEmpty(fileName) || Filedata.ContentLength < 1)
            {
                return Json(new { Success = false, Message = "上传的文件字节数为0" }, "text/html", JsonRequestBehavior.AllowGet);
            }
            if (Filedata.ContentLength > maxFileSize * 1024)
            {
                return Json(new { Success = false, Message = "上传的文件大小超过限制，请上传2M以内的图片！" }, "text/html", JsonRequestBehavior.AllowGet);
            }

            string fileExt = fileName.Substring(fileName.LastIndexOf(".") + 1).ToLower();
            string newFileName = this.MD5(DateTime.Now.ToString() + new Random().Next(0, 20)).Substring(8, 16).Replace(".", string.Empty).Trim();

            string path = string.Concat(uploadPath, (DateTime.Now.ToString("yyyyMM")), "/");
            if (!Directory.Exists(Server.MapPath(path)))
            {
                Directory.CreateDirectory(Server.MapPath(path));
            }
            string filepath = path + newFileName + "." + fileExt;
            Filedata.SaveAs(Server.MapPath(filepath));

            return Json(filepath, "text/html", JsonRequestBehavior.AllowGet);
        }


        private string MD5(string key)
        {
            System.Security.Cryptography.MD5 md5 = new System.Security.Cryptography.MD5CryptoServiceProvider();
            byte[] bytResult = md5.ComputeHash(System.Text.Encoding.UTF8.GetBytes(key));
            string strResult = BitConverter.ToString(bytResult);

            //BitConverter转换出来的字符串会在每个字符中间产生一个分隔符，需要去除掉 
            strResult = strResult.Replace("-", "");
            return strResult;
            //return System.Web.Security.FormsAuthentication.HashPasswordForStoringInConfigFile(key, "MD5");
        } 

    }
}

src/Goceen.Website.Web/Views/Category/AddOrEdit.cshtml
@model Goceen.Website.Domain.SysCategory
@{
    ViewBag.Title = "AddOrEdit";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
    var urlisshow = (Model.CategoryType == Goceen.Website.Domain.CategoryType.url) ? "" : "display:none";
    var contentisshow = (Model.CategoryType == Goceen.Website.Domain.CategoryType.content) ? "" : "display:none";
}

<div id="DivAddType" style="width:96%;margin:10px auto;">
    @using (Html.BeginForm("Save", "Category", FormMethod.Post, new { @id = "form" }))
    {
        @Html.AntiForgeryToken()
        <table id="tblAddBatch" class="view" style="width:98%">
            <tr>
                <th>
                    <label for="name">分类名称：</label>
                </th>
                <td>
                    @Html.HiddenFor(m => m.Id)
                    @Html.EasyuiInput(m => m.Name, new { @class = "easyui-validatebox" })
                </td>
                <th>
                    <label for="channel">所属频道：</label>
                </th>
                <td>
                    @Html.DropDownList("channelId", (List<SelectListItem>)ViewBag.ChannelList, new {  @class = "easyui-validatebox" })
                    @*@Html.DropDownListFor(m => m.Channel, (List<SelectListItem>)ViewBag.ChannelList ,new { name="channelId", id="channelId", @class = "easyui-validatebox"  })*@
                </td>    
            </tr>        
            <tr>                
                <th>
                    <label>类型：</label>
                </th>
                <td>
                    @Html.DropDownListFor(m => m.CategoryType, (List<SelectListItem>)ViewBag.CategoryType, new { id = "categorytype", @class = "easyui-validatebox easyui-combobox" })
                    &nbsp;&nbsp;@Html.EasyuiInput(m => m.Url, new { @class = "easyui-validatebox", sytle = urlisshow })
                </td>
                <th>
                    <label for="orderno">排序：</label>
                </th>
                <td>
                    @*<input class="easyui-validatebox" data-options="required:true,validType:['number','range[0,999,\'排列序号必须是0-999之间\']']" id="OrderNo" name="OrderNo" />*@
                    @Html.EasyuiInput(m => m.OrderNo, new { @class = "easyui-validatebox" })
                </td>
            </tr>
            <tr>
                <th>
                    <label>关键字：</label>
                </th>
                <td>
                    @Html.EasyuiInput(m => m.Keyword, new { @class = "easyui-validatebox" })
                </td>
                <th>
                    <label>是否显示</label>
                </th>
                <td>
                    @Html.CheckBoxFor(m => m.IsEnabled, new { @checked = "checked" })
                </td>
            </tr>
            <tr id="showeditor" style="@contentisshow">
                <th>
                    <label for="Description">内容：</label>
                </th>
                <td colspan="3">
                    @Html.TextAreaFor(m => m.Content, new { style = "height:300px;width: 500px", id = "content" })

                </td>
            </tr>
            <tr>
                <td colspan="4" style="text-align:right; padding-top:10px">
                    <a href="javascript:void(0)" class="easyui-linkbutton" id="btnAddOKType" iconcls="icon-ok">确定</a>
                    <a href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-cancel" onclick="javascript: $('#modalwindow').window('close')">关闭</a>
                </td>
            </tr>
        </table>
    }
</div>
@section Scripts {
    <script type="text/javascript" charset="utf-8">window.UMEDITOR_HOME_URL = "@Url.Content("~/Scripts/umeditor/")";</script>
    <script src="@Url.Content("~/Scripts/umeditor/umeditor.config.js")" type="text/javascript" charset="utf-8"></script>
    <script src="@Url.Content("~/Scripts/umeditor/umeditor.min.js")" type="text/javascript" charset="utf-8"></script>
    <link href="@Url.Content("~/Scripts/umeditor/themes/default/css/umeditor.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/umeditor/lang/zh-cn/zh-cn.js")" type="text/javascript" charset="utf-8"></script> 
    <script type="text/javascript">
        $(function () {
            $("#categorytype").combobox({
                onChange: function () {
                    var value =  $('#categorytype').combobox('getValue');
                    if (value==4){
                        $("#Url").hide();
                        $("#showeditor").show();
                        setEditor();
                    }
                    else{
                        $("#Url").show();                        
                        $("#showeditor").hide();
                    }
                }
            });
        });
        

        function setEditor()
        {
            var editor = UM.getEditor('content', {
                imageUrl: "@Url.Action("UmeditorUploadImg", "Upload")",
                imagePath:""
            });
        }

        $("#btnAddOKType").click(function () {
            var form = $("#form");
            if (form.form("validate")) {
                $.ajax({
                    debug: true,
                    url: "/Category/Save",
                    type: "Post",
                    data: form.serialize(),
                    dataType: "json",
                    success: function (data) {
                        if (data.Success) {
                            //form.form("clear");
                            $.messager.alert('提示', data.Message, "info", function () {
                                $("#modalwindow").window('close');
                                $('#grid').datagrid("reload");
                            });
                        }
                        else {
                            $.messager.alert("提示", data.Message);
                        }
                    }
                });
            }
            return false;
        });

    </script>
}

src/Goceen.Website.Web/Views/Category/Admin.cshtml
@{
    
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div region="center" style="padding: 5px;" border="false">
    <table id="grid"></table>
</div>
<div id="modalwindow" data-options="modal:true,closed:true,minimizable:false,shadow:false"></div>
@section Scripts {
    <script type="text/javascript" src="@Url.Content("~/Scripts/ViewScripts/category.js")"></script>
}