src/Goceen.Website.Web/Controllers/IconController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Goceen.Website.Services;
using Goceen.Website.Domain;
using Leon.Core.Cache;
using Goceen.Website.Web.Extensions;
using System.IO;

namespace Goceen.Website.Web.Controllers
{
    public class IconController : BaseController
    {

        public IconController(ISysConfigService config, ICacheManager cache, ISysUserService user,
            ISysIconService icon)
        {
            _cacheManager = cache;
            _sysuserSerice = user;
            _sysconfigService = config;
            _sysiconService = icon;

        }

        [Authorize]
        public ActionResult Admin()
        {
            ViewBag.Title = "图标管理";
            return View();
        }

        [Authorize]
        public ActionResult LoadAllByPage(int page, int rows, string order, string sort)
        {
            long total = 0;
            var list = base._sysiconService.LoadAllByPage(out total, page, rows, order, sort).Select(entity => new
            {
                entity.Title,
                entity.Id,
                entity.Img,
                entity.Url,
                entity.IsEnabled,
                entity.OrderNo
            });

            var result = new { total = total, rows = list.ToList() };
            return Json(result);
        }

        [Authorize]
        public ActionResult AddOrEdit(int? id)
        {
            var list = base._sysiconService.LoadAllEnable();    

            SysIcon entity = null;
            if (!string.IsNullOrEmpty(id.ToString()))
            {
                entity = base._sysiconService.Get(Convert.ToInt32(id));
            }
            entity = entity ?? new SysIcon
            {
                Title = string.Empty,
            };
            return View(entity);
        }

        [Authorize]
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Save(SysIcon entity)
        {

            

            if (entity.Id == 0)
            {
                if (_sysiconService.IsExist(entity.Id))
                {
                    return Json(new CommonResult
                    {
                        Success = false,
                        Message = "标题已经存在，请重新输入！"
                    }, "text/html", JsonRequestBehavior.AllowGet);
                }
                base._sysiconService.Save(entity);
            }
            else
            {
                var model = base._sysiconService.Get(entity.Id);
                model.Title = entity.Title;
                model.Img = entity.Img;
                model.OrderNo = entity.OrderNo;
                model.Url = entity.Url;
                model.IsEnabled = entity.IsEnabled;
                base._sysiconService.Update(model);
            }

            return Json(new CommonResult { Success = true, Message = "保存成功" }, "text/html", JsonRequestBehavior.AllowGet);
        }

        //public ActionResult Show(int id)
        //{
        //    var entity = base._sysiconService.Get(id);
        //    if (entity == null)
        //    {
        //        return Redirect(this.Request.UrlReferrer.ToString());
        //    }
        //    var categoryList = base._syscategoryService.LoadAllEnable(entity.Category.Channel.Id);
        //    ViewBag.entity = entity;
        //    ViewBag.Category = base._syscategoryService.Get(entity.Category.Id);
        //    ViewBag.CateId = entity.Category.Id;
        //    ViewBag.ChannelInfo = entity.Category.Channel;
        //    ViewBag.CateList = categoryList;
        //    base._sysiconService.ViewsAdd(id);
        //    return View();
        //}

        [Authorize]
        public ActionResult Delete(IList<int> idList)
        {
            base._sysiconService.Delete(idList.Cast<int>().ToList());
            return Json(new CommonResult { Success = true, Message = "删除成功" });
        }


        [HttpPost]
        public JsonResult Upload(HttpPostedFileBase upImg)
        {
            string fileName = Path.GetFileName(upImg.FileName);
            string filePhysicalPath = Server.MapPath("~/upload/" + fileName);
            string pic = "", error = "";
            try
            {
                upImg.SaveAs(filePhysicalPath);
                pic = "/upload/" + fileName;
            }
            catch (Exception ex)
            {
                error = ex.Message;
            }
            return Json(new
            {
                pic = pic,
                error = error
            });
        }

        public ActionResult TestUpload()
        {
            return View();
        }
    }
}

src/Goceen.Website.Web/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;
using System.Web.Mvc;
using System.Web.Security;
using Newtonsoft.Json;

namespace Goceen.Website.Web.Controllers
{
    public class UploadController : Controller
    {
        //
        // GET: /Upload/

        protected readonly int maxFileSize = 20480;

        protected readonly string allowFile = "gif,jpg,jpeg,bmp,png";

        protected readonly string uploadPath = "/Content/Upload/image/";

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult UmeditorUploadImg()
        {
            HttpFileCollectionBase files= Request.Files;

            if (files.Count == 0)
            {               
                return Json(new { Success = false, state = "没有选择要上传的文件",URL="" }, "text/html", JsonRequestBehavior.AllowGet);
            }
            HttpPostedFileBase Filedata = files[0];
            string fileName = System.IO.Path.GetFileName(Filedata.FileName);
            // 0字节文件
            if (string.IsNullOrEmpty(fileName) || Filedata.ContentLength < 1)
            {
                return Json(new { Success = false, state = "上传的文件字节数为0" ,URL=""}, "text/html", JsonRequestBehavior.AllowGet);
            }
            if (Filedata.ContentLength > maxFileSize * 1024)
            {
                return Json(new { Success = false, state = "上传的文件大小超过限制，请上传2M以内的图片！", URL = "" }, "text/html", JsonRequestBehavior.AllowGet);
            }

            string fileExt = fileName.Substring(fileName.LastIndexOf(".") + 1).ToLower();
            string newFileName = this.MD5(DateTime.Now.ToString() + new Random().Next(0, 20)).Substring(8, 16).Replace(".", string.Empty).Trim();

            string path = string.Concat(uploadPath, (DateTime.Now.ToString("yyyyMM")), "/");
            if (!Directory.Exists(Server.MapPath(path)))
            {
                Directory.CreateDirectory(Server.MapPath(path));
            }
            string filepath = path + newFileName + "." + fileExt;
            Filedata.SaveAs(Server.MapPath(filepath));

            return Json(new { state = "SUCCESS", url = filepath }, "text/html", JsonRequestBehavior.AllowGet);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult UploadImg(HttpPostedFileBase Filedata)
        {


            if (Filedata == null || string.IsNullOrEmpty(Filedata.FileName) || Filedata.ContentLength == 0)
            {
                return Json(new { Success = false, Message = "没有选择要上传的文件" }, "text/html", JsonRequestBehavior.AllowGet);
            }
            string fileName = System.IO.Path.GetFileName(Filedata.FileName);
            // 0字节文件
            if (string.IsNullOrEmpty(fileName) || Filedata.ContentLength < 1)
            {
                return Json(new { Success = false, Message = "上传的文件字节数为0" }, "text/html", JsonRequestBehavior.AllowGet);
            }
            if (Filedata.ContentLength > maxFileSize * 1024)
            {
                return Json(new { Success = false, Message = "上传的文件大小超过限制，请上传2M以内的图片！" }, "text/html", JsonRequestBehavior.AllowGet);
            }

            string fileExt = fileName.Substring(fileName.LastIndexOf(".") + 1).ToLower();
            string newFileName = this.MD5(DateTime.Now.ToString() + new Random().Next(0, 20)).Substring(8, 16).Replace(".", string.Empty).Trim();

            string path = string.Concat(uploadPath, (DateTime.Now.ToString("yyyyMM")), "/");
            if (!Directory.Exists(Server.MapPath(path)))
            {
                Directory.CreateDirectory(Server.MapPath(path));
            }
            string filepath = path + newFileName + "." + fileExt;
            Filedata.SaveAs(Server.MapPath(filepath));

            return Json(filepath, "text/html", JsonRequestBehavior.AllowGet);
        }


        private string MD5(string key)
        {
            System.Security.Cryptography.MD5 md5 = new System.Security.Cryptography.MD5CryptoServiceProvider();
            byte[] bytResult = md5.ComputeHash(System.Text.Encoding.UTF8.GetBytes(key));
            string strResult = BitConverter.ToString(bytResult);

            //BitConverter转换出来的字符串会在每个字符中间产生一个分隔符，需要去除掉 
            strResult = strResult.Replace("-", "");
            return strResult;
            //return System.Web.Security.FormsAuthentication.HashPasswordForStoringInConfigFile(key, "MD5");
        } 

    }
}

src/Goceen.Website.Web/Views/Icon/AddOrEdit.cshtml
@model Goceen.Website.Domain.SysIcon
@{
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}
<div id="DivAddType" style="width:370px;height:280px;margin:10px;">
    @using (Html.BeginForm("Save", "Icon", FormMethod.Post, new { @id = "form" }))
    {
        @Html.AntiForgeryToken()
        <table id="tblAddBatch" class="view" style="width:98%">
            <tr>
                <th>
                    <label for="name">标题：</label>
                </th>
                <td>
                    @Html.HiddenFor(m => m.Id)
                    @Html.EasyuiInput(m => m.Title, new { @class = "easyui-validatebox" })
                </td>
            </tr>
            <tr>
                <th>
                    <label for="orderno">链接：</label>
                </th>
                <td>
                    @Html.EasyuiInput(m => m.Url, new { @class = "easyui-validatebox" })
                </td>
            </tr>
            <tr>
                <th>
                    <label>推荐图：</label>
                </th>
                <td colspan="3">
                    <input type="file" id="uploadfile" />
                    @Html.HiddenFor(m => m.Img)
                    <div id="fileQueue"></div>
                </td>
            </tr>  
            <tr>
                <th>
                    <label for="name">排序：</label>
                </th>
                <td>
                    @Html.EasyuiInput(m => m.OrderNo, new { @class = "easyui-validatebox" })
                </td>
            </tr>
            <tr>
                <th>
                    <label>是否启用</label>
                </th>
                <td>
                    @Html.CheckBoxFor(m => m.IsEnabled, new { @checked = "checked" })
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align:right; padding-top:10px">
                    <a href="javascript:void(0)" class="easyui-linkbutton" id="btnAddOKType" iconcls="icon-ok">确定</a>
                    <a href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-cancel" onclick="javascript: $('#modalwindow').window('close')">关闭</a>
                </td>
            </tr>
        </table>
    }
</div>

    <script type="text/javascript" charset="utf-8">window.UMEDITOR_HOME_URL = "@Url.Content("~/Scripts/umeditor/")";</script>
    <script src="@Url.Content("~/Scripts/umeditor/umeditor.config.js")" type="text/javascript" charset="utf-8"></script>
    <script src="@Url.Content("~/Scripts/umeditor/umeditor.min.js")" type="text/javascript" charset="utf-8"></script>
    <link href="@Url.Content("~/Scripts/umeditor/themes/default/css/umeditor.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/umeditor/lang/zh-cn/zh-cn.js")" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript" src="/Scripts/uploadify/jquery.uploadify.min.js"></script>
    <link type="text/css" rel="Stylesheet" href="@Url.Content("~/Scripts/uploadify/uploadify.css")" />
    <script type="text/javascript">
    $(function () {
        var editor = UM.getEditor('content', {
            imageUrl: "@Url.Action("UmeditorUploadImg", "Upload")",
            imagePath: ""
        });
        var auth = "@(Request.Cookies[FormsAuthentication.FormsCookieName]==null?string.Empty:Request.Cookies[FormsAuthentication.FormsCookieName].Value)";
        var ASPSESSID = "@(Session.SessionID )";
        $('#uploadfile').uploadify({
            swf: '/Scripts/uploadify/uploadify.swf?m=' + Math.random(),
            uploader: '/upload/UploadImg',
            cancelImg: '/Scripts/uploadify/uploadify-cancel.png',
            fileObjName: 'Filedata',
            buttonTex: '选择文件',
            formData: { 'type': 'pic' },
            auto: true,
            fileTypeExts: "*.jpg;*.png;*.bmp;*.gif;*.pic;*.jpeg",             // 扩展名
            fileTypeDesc: "请选择 jpg png bmp gif pic文件",     // 文件说明
            queueID: 'fileQueue',
            multi: false,
            removeCompleted: false,
            onUploadSuccess: function (file, data, response) {
                var picpath = eval(data);
                $('#Img').val(picpath);
            },
            onUploadError: function (file, errorCode, errorMsg, errorString) {
                $.messager.alert("提示", errorMsg);
            }
        });

    });

            $("#btnAddOKType").click(function () {
                var form = $("#form");
                if (form.form("validate")) {
                    $.ajax({
                        debug: true,
                        url: "/Icon/Save",
                        type: "Post",
                        data: form.serialize(),
                        dataType: "json",
                        success: function (data) {
                            if (data.Success) {
                                //form.form("clear");
                                $.messager.alert('提示', data.Message, "info", function () {
                                    $("#modalwindow").window('close');
                                    $('#grid').datagrid("reload");

                                });
                            }
                            else {
                                $.messager.alert("提示", data.Message);
                            }
                        }
                    });
                }
                return false;
            });

    </script>
@*<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.form.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
<script type="text/javascript">
        $(function () {
            $("#btn_show").bind("click", function () {
                $("#form_upload").show();
                var options = {
                    success: function (responseText, statusText, xhr, $form) {
                        var picPath = responseText.pic;
                        $('#Img').val(picPath);
                        if (picPath == "") {
                            alert(responseText.error);
                        }
                        else {
                            $("#form_upload").hide();
                            $("#result").attr("src", picPath).show();
                        }
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        console.log(textStatus);
                        console.log(errorThrown);
                    }
                };
                $("#form_upload").ajaxForm(options);
            });
        });
</script>*@

src/Goceen.Website.Web/Views/Icon/Admin.cshtml
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div region="center" style="padding: 5px;" border="false">
<table id="grid"></table>
</div>
<div id="modalwindow" data-options="modal:true,closed:true,minimizable:false,shadow:false"></div>
@section Scripts {
    <script type="text/javascript" src="@Url.Content("~/Scripts/ViewScripts/icon.js")"></script>
}

<style type="text/css">
    .datagrid-sort-desc .datagrid-sort-icon {
        padding: 0 13px 0 0;
        background: none;
    }
</style>

src/Goceen.Website.Web/Views/Icon/TestUpload.cshtml
@{
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.form.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
    <script type="text/javascript">
        $(function () {
            $("#btn_show").bind("click", function () {
                $("#form_upload").show();
                var options = {
                    success: function (responseText, statusText, xhr, $form) {
                        var picPath = responseText.pic;
                        if (picPath == "") {
                            alert(responseText.error);
                        }
                        else {
                            $("#form_upload").hide();
                            $("#result").attr("src", picPath).show();
                        }
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        console.log(textStatus);
                        console.log(errorThrown);
                    }
                };
                $("#form_upload").ajaxForm(options);
            });
        });
    </script>

<input type="button" id="btn_show" value="上传图片" /><br />
<form id="form_upload" style="padding:20px;" action="Upload" method="post" enctype="multipart/form-data">
    <input name="upImg" style="width:350px;height:25px;" size="38" type="file" /><input type="submit" value="上传" />
</form>
<img alt="" style="display:none;" id="result" src="" />

<input name="upImgs" style="width:350px;height:25px;" size="38" type="file" /><input type="submit" value="上传" />